### PR TITLE
non-interactive mode for systemd

### PR DESCRIPTION
**Pull request by desaster**
I couldn't get the sftdyn to run via systemd without these changes, since systemd closes stdin upon start.

Also included a sample systemd script.

### CODE REVIEW

**Comment by TheJJ** [comment]
thanks, that's a good idea.
i fear it's not good to join the server right after creation, the execution won't reach the https server that way.
your commits are not associated to your account btw.
maybe we should change the install path in the systemd unit so it works properly when packaged properly.

**Comment by desaster** [comment]
I'm not sure what is the proper way to handle this. However, this patch is a quick hack anyway, since I think when not using the interactive feature, there is no need for the threading at all.

I'm not sure what the intended use for the interactive console is, but personally I would simplify things and remove it completely.

**Comment by TheJJ** [comment]
Yes, we should remove the interactive mode alltogether, i think mic_e used it for debugging mainly.

**Comment by TheJJ** [comment]
I rewrote the software to no longer use threads, and I removed the interactive console.
The readme also includes the systemd unit file templates now :)

**Pull request closed without merging**
