### PR TITLE
Ability to optionally provide a custom key for nsupdate

### PR DESCRIPTION
**Pull request by desaster**
This PR implements the feature requested in the issue #13.

New option `--nskeyfile` can be used to provide a pre-generated keyfile, which will be then passed to nsupdate using the `-k` argument.

```
-k keyfile
   The file containing the TSIG authentication key. Keyfiles may be in two formats: a
   single file containing a named.conf-format key statement, which may be generated
   automatically by ddns-confgen, or a pair of files whose names are of the format
   K{name}.+157.+{random}.key and K{name}.+157.+{random}.private, which can be generated
   by dnssec-keygen. The -k may also be used to specify a SIG(0) key used to authenticate
   Dynamic DNS update requests. In this case, the key specified is not an HMAC-MD5 key.
```

Open for suggestions, changes or a complete takeover of the PR.

This to consider:

* Is the documentation clear? I consider custom keyfile to be an important feature, but I'm not sure if the users understand when or why to use it.
* I named the argument `--nskeyfile` with no shorthand, since `-k` is already taken.
* I may have forgotten some details about this, since I originally wrote the issue a year ago. Could probably use some testing.

### CODE REVIEW

**Review by TheJJ — CHANGES_REQUESTED** [review]
Thank you :)
The documentation is alright!

In general, I think we should rather pass the keyfile as argument in the sftdyn config file, where we can customize the nsupdate command anyway. Then one does not need to modify the systemd unit and invocation, but instead just write it in the sftdyn config. What are your thoughts on that?

**Comment by desaster** [comment]
It turns out the nskeyfile option was already usable from the conf file, but I had forgotten about it. I changed the documentation to use the config instead of overriding the systemd unit.

**Review by TheJJ — APPROVED** [review]
great!

**Comment by TheJJ** [comment]
Unless you have any additions, we can merge it. Maybe, as a future extension, we can allow to specify arbitrary additional command line options in the config file.

**Comment by desaster** [comment]
I have nothing else planned.

Yes, I suppose the whole feature could be replaced by a setting that lets you specify nsupdate parameters.

**Pull request merged**
